# Generated by Django 4.2.4 on 2023-08-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kandidat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('ime', models.TextField(max_length=256)),
                ('brglasova', models.IntegerField()),
            ],
        ),
    ]
