# Generated by Django 4.2.4 on 2023-08-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glasanje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glas',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('glasao', models.BooleanField()),
            ],
        ),
    ]
