# Generated by Django 4.2.4 on 2023-08-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teretana', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vezba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=256)),
                ('opis', models.CharField(max_length=14000)),
                ('program', models.IntegerField()),
            ],
        ),
    ]
